---
- name: Deploy Flask App
  hosts: all
  become: yes
  tasks:
    - name: Ensure Python and pip are installed
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask
        executable: pip3

    - name: Copy Flask application
      copy:
        src: "{{ playbook_dir }}/../web-app/app.py"
        dest: /home/ec2-user/app.py

    - name: Create a systemd service file for Flask app
      copy:
        content: |
          [Unit]
          Description=Flask Web Application
          After=network.target

          [Service]
          User=root
          WorkingDirectory=/home/ec2-user
          ExecStart=/usr/bin/python3 /home/ec2-user/app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/flask_app.service

    - name: Start and enable Flask service
      systemd:
        name: flask_app
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Ensure Flask app is running
      wait_for:
        port: 80
        delay: 5
        timeout: 30